services:
  - type: web
    name: audit-hormonal-platform
    runtime: node
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ANTHROPIC_MAX_TOKENS_GRATUIT
        value: "5000"
      - key: ANTHROPIC_MAX_TOKENS_PREMIUM
        value: "16000"
      - key: ANTHROPIC_MAX_TOKENS_HORMONAL_GRATUIT
        value: "3000"
      - key: ANTHROPIC_MAX_TOKENS_HORMONAL_PREMIUM
        value: "10000"
      - key: EMAIL_FROM
        value: coaching@achzodcoaching.com
      - key: DATABASE_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: SENDPULSE_API_ID
        sync: false
      - key: SENDPULSE_API_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false

